### ISSUE TITLE
Do you foget to upload the ''model'' folder?

### ISSUE THREAD

**Issue by chang-cai** [poopbear/split-learning#1]
Hi,
I'm trying to run the code, but an error occurs
"FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Split Learning\\split-learning-1d-cnn-master\\split-learning-1d-cnn-master\\model\\conv3_0_best.pth'"
I cannot find the 'model' folder in the repository. Does it mean you forget to upload?

Thanks.

**Comment by kyuyeonpooh** [comment]
Hi, I'm VERY sorry for the late reply.
Could you specify the name of the file which you had a problem with?

I guess your problematic file might be `adding_layers/ecg_train_3conv_10run.ipynb`, which repeatedly run the code that trains 1D CNN ECG classifier 10 times and save those into the `model` directory.
**Yes, that's my bad and you should make a directory `model` in your working directory:**
```
mkdir model
```

By the way, I found that I already had saved some pretrained results (which you may be looking for) in my Google Drive.
Please refer [HERE](https://drive.google.com/drive/folders/1dmzV7ejwjcC_FjsvB_w9wdJCNep3Ewdt?usp=sharing) and check if there is anything you are looking for!

I hope this helps.
